In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [45]:
# Load the data
df = pd.read_csv('CreditCardData.csv')

Attrited Customers. There are 1627 Attrited Customers out of 10127. Mean Revolving balance is 672. Mean contacts in 21 months is ~3. Max Months inactive is 6. These seem to be the customers who have closded the account or had their accounts locked pending payment. We might want to factor in how likely it is that they will repay the balance and interest. Demographics seem similar between Attrited and Existing.

In [46]:
Attrited_Customers = df[df['Attrition_Flag'] == 'Attrited Customer']
Attrited_Customers.describe()

,CLIENTNUM,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
count,1.627000e+03,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000
mean,7.352614e+08,46.659496,2.402581,36.178242,3.279656,2.693301,2.972342,8136.039459,672.822987,7463.216472,0.694277,3095.025814,44.933620,0.554386,0.162475
std,3.557725e+07,7.665652,1.275010,7.796548,1.577782,0.899623,1.090537,9095.334105,921.385582,9109.208129,0.214924,2308.227629,14.568429,0.226854,0.264458
min,7.080833e+08,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000
25%,7.123713e+08,41.000000,2.000000,32.000000,2.000000,2.000000,2.000000,2114.000000,0.000000,1587.000000,0.544500,1903.500000,37.000000,0.400000,0.000000
50%,7.165644e+08,47.000000,2.000000,36.000000,3.000000,3.000000,3.000000,4178.000000,0.000000,3488.000000,0.701000,2329.000000,43.000000,0.531000,0.000000
75%,7.683737e+08,52.000000,3.000000,40.000000,5.000000,3.000000,4.000000,9933.500000,1303.500000,9257.500000,0.856000,2772.000000,51.000000,0.692000,0.231000
max,8.282949e+08,68.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,1.492000,10583.000000,94.000000,2.500000,0.999000

In [47]:
Existing_Customers = df[df['Attrition_Flag'] == 'Existing Customer']
Existing_Customers.describe()

,CLIENTNUM,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
count,8.500000e+03,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000
mean,7.399272e+08,46.262118,2.335412,35.880588,3.914588,2.273765,2.356353,8726.877518,1256.604118,7470.273400,0.772510,4654.655882,68.672588,0.742434,0.296412
std,3.710723e+07,8.081157,1.303229,8.021810,1.528949,1.016741,1.081436,9084.969807,757.745354,9087.671862,0.217783,3512.772635,22.919011,0.228054,0.272568
min,7.080821e+08,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,15.000000,0.256000,816.000000,11.000000,0.028000,0.000000
25%,7.132197e+08,41.000000,1.000000,31.000000,3.000000,1.000000,2.000000,2602.000000,800.000000,1184.500000,0.643000,2384.750000,54.000000,0.617000,0.055000
50%,7.181643e+08,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4643.500000,1364.000000,3469.500000,0.743000,4100.000000,71.000000,0.721000,0.211000
75%,7.783415e+08,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11252.750000,1807.000000,9978.250000,0.860000,4781.250000,82.000000,0.833000,0.529250
max,8.283431e+08,73.000000,5.000000,56.000000,6.000000,6.000000,5.000000,34516.000000,2517.000000,34516.000000,3.397000,18484.000000,139.000000,3.714000,0.994000

In [48]:
# Load the data
df = pd.read_csv('CreditCardData.csv')

# change the data type of the columns to float
df['Attrition_Flag'] = df['Attrition_Flag'].map({'Existing Customer': 0, 'Attrited Customer': 1})
df['Gender'] = df['Gender'].map({'M': 1, 'F': 0})
df['Education_Level'] = df['Education_Level'].map({'High School': 0, 'Graduate': 1, 'Uneducated': 2, 'College': 3, 'Post-Graduate': 4, 'Doctorate': 5, 'Unknown': 6})
df['Marital_Status'] = df['Marital_Status'].map({'Married': 0, 'Single': 1, 'Divorced': 2, 'Unknown': 3})
df['Income_Category'] = df['Income_Category'].map({'Less than $40K': 0, '$40K - $60K': 1, '$60K - $80K': 2, '$80K - $120K': 3, '$120K +': 4, 'Unknown': 5})
df['Card_Category'] = df['Card_Category'].map({'Blue': 0, 'Silver': 1, 'Gold': 2, 'Platinum': 3})

In [49]:
df.shape

(10127, 21)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CLIENTNUM                 10127 non-null  int64
 1   Attrition_Flag            10127 non-null  int64
 2   Customer_Age              10127 non-null  int64
 3   Gender                    10127 non-null  int64
 4   Dependent_count           10127 non-null  int64
 5   Education_Level           10127 non-null  int64
 6   Marital_Status            10127 non-null  int64
 7   Income_Category           10127 non-null  int64
 8   Card_Category             10127 non-null  int64
 9   Months_on_book            10127 non-null  int64
 10  Total_Relationship_Count  10127 non-null  int64
 11  Months_Inactive_12_mon    10127 non-null  int64
 12  Contacts_Count_12_mon     10127 non-null  int64
 13  Credit_Limit              10127 non-null  float64
 14  Total_Revolving_Bal       10127 non-null  int64
 15  Avg_Open_To_Buy           10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1      10127 non-null  float64
 17  Total_Trans_Amt           10127 non-null  int64
 18  Total_Trans_Ct            10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1       10127 non-null  float64
 20  Avg_Utilization_Ratio     10127 non-null  float64
dtypes: float64(5), int64(16)
memory usage: 1.6 MB

What % of CC useres carry a balance?

In [119]:
non_zero_count = df[df['Total_Revolving_Bal'] != 0].shape[0]
total_count = df.shape[0]
percentage_all_customers = (non_zero_count / total_count) * 100


# Calculate the percentage of non-zero revolving balance for attrited customers
attrited_non_zero_count = Attrited_Customers[Attrited_Customers['Total_Revolving_Bal'] != 0].shape[0]
attrited_percentage = (attrited_non_zero_count / Attrited_Customers.shape[0]) * 100

# Calculate the percentage of non-zero revolving balance for existing customers
existing_non_zero_count = Existing_Customers[Existing_Customers['Total_Revolving_Bal'] != 0].shape[0]
existing_percentage = (existing_non_zero_count / Existing_Customers.shape[0]) * 100

# Create a dictionary to store the percentages
percentages = {
    'All Customers': percentage_all_customers,
    'Attrited Customers': attrited_percentage,
    'Existing Customers': existing_percentage
}

percentages

{'All Customers': 75.60975609756098,
 'Attrited Customers': 45.113706207744315,
 'Existing Customers': 81.44705882352942}

In [128]:
import pandas as pd
zero_balance_attrited_customers = Attrited_Customers[Attrited_Customers['Total_Revolving_Bal'] == 0]
non_zero_balance_attrited_customers = Attrited_Customers[Attrited_Customers['Total_Revolving_Bal'] != 0]

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
39,708300483,Attrited Customer,66,F,0,Doctorate,Married,Unknown,Blue,56,5,4,3,7882.0,605,7277.0,1.052,704,16,0.143,0.077
51,779471883,Attrited Customer,54,F,1,Graduate,Married,Less than $40K,Blue,40,2,3,1,1438.3,808,630.3,0.997,705,19,0.900,0.562
99,711887583,Attrited Customer,47,M,2,Unknown,Married,$80K - $120K,Blue,37,2,3,3,5449.0,1628,3821.0,0.696,836,18,0.385,0.299
127,720201033,Attrited Customer,53,M,2,Graduate,Married,$80K - $120K,Blue,41,3,3,2,11669.0,2227,9442.0,0.622,720,23,0.353,0.191
168,713741358,Attrited Customer,46,M,5,Graduate,Single,$80K - $120K,Blue,33,6,3,3,32975.0,2517,30458.0,0.658,597,17,0.700,0.076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10113,713733633,Attrited Customer,27,M,0,High School,Divorced,$60K - $80K,Blue,36,2,3,2,13303.0,2517,10786.0,0.929,10219,85,0.809,0.189
10118,713755458,Attrited Customer,50,M,1,Unknown,Unknown,$80K - $120K,Blue,36,6,3,4,9959.0,952,9007.0,0.825,10310,63,1.100,0.096
10119,716893683,Attrited Customer,55,F,3,Uneducated,Single,Unknown,Blue,47,4,3,3,14657.0,2517,12140.0,0.166,6009,53,0.514,0.172
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [126]:
attrited_zero_balance_count = zero_balance_attrited_customers.shape[0]
attrited_percentage_zero_balance = (attrited_zero_balance_count / Attrited_Customers.shape[0]) * 100
attrited_percentage_zero_balance

54.88629379225568

### Logistic Regression

In [194]:
df_clean = Existing_Customers.append(non_zero_balance_attrited_customers)
df_clean.shape

C:\Users\nfs25\AppData\Local\Temp\ipykernel_18644\2707584716.py:1: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

(9234, 21)

In [195]:
from sklearn.preprocessing import LabelEncoder
encoder  = LabelEncoder()

df_clean['Attrition_Flag'] = encoder.fit_transform(df_clean['Attrition_Flag'])
df_clean["Education_Level"] = encoder.fit_transform(df_clean['Education_Level'])
df_clean["Gender"] = encoder.fit_transform(df_clean["Gender"])
df_clean["Marital_Status"] = encoder.fit_transform(df_clean["Marital_Status"])
df_clean['Income_Category'] = encoder.fit_transform(df_clean['Income_Category'])
df_clean['Card_Category'] = encoder.fit_transform(df_clean['Card_Category'])

df_clean = df_clean.drop('CLIENTNUM', axis=1)

In [211]:
df_clean

,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,1,45,1,3,3,1,2,0,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,1,49,0,5,2,2,4,0,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,1,51,1,3,2,1,3,0,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,1,40,0,4,3,3,4,0,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,1,40,1,3,5,1,2,0,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10113,0,27,1,0,3,0,2,0,36,2,3,2,13303.0,2517,10786.0,0.929,10219,85,0.809,0.189
10118,0,50,1,1,6,3,3,0,36,6,3,4,9959.0,952,9007.0,0.825,10310,63,1.100,0.096
10119,0,55,0,3,5,2,5,0,47,4,3,3,14657.0,2517,12140.0,0.166,6009,53,0.514,0.172
10123,0,41,1,2,6,0,1,0,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10126,0,43,0,2,2,1,4,3,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [196]:
from sklearn.model_selection import train_test_split

df_clean_X = df_clean[df_clean.columns[1:]]
df_clean_y = df_clean[df_clean.columns[0]]

X_train, X_test, y_train, y_test = train_test_split(df_clean_X, df_clean_y , test_size=0.2, random_state=42)

In [206]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)

RFC.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [207]:
# Predict on the test set
y_pred = pd.DataFrame(RFC.predict(X_test))
y_pred_proba = pd.DataFrame(RFC.predict_proba(X_test)[:, 1])
#y_pred_proba = y_pred_proba.rename(columns={0: 'Attrited Customer'})
#y_pred_proba = y_pred_proba.rename(columns={1: 'Existing Customer'})

In [208]:
y_pred.value_counts()

1    1749
0      98
dtype: int64

In [209]:
y_pred_proba

         0
0     1.00
1     1.00
2     1.00
3     0.83
4     1.00
...    ...
1842  0.94
1843  1.00
1844  1.00
1845  0.99
1846  1.00

[1847 rows x 1 columns]

In [202]:
from sklearn.metrics import accuracy_score, roc_auc_score

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred_proba)

# Print performance metrics
print(f'Accuracy: {accuracy}')
print(f'ROC-AUC: {roc_auc}')

Accuracy: 0.9702219815917704
ROC-AUC: 0.9857234330163398

In [203]:
import plotly.express as px
fig = px.histogram(y_pred_proba, x=0)
fig.show()

In [182]:
df_clean_year_2 = df_clean.copy()
df_clean_year_2['Customer_Age'] = df_clean['Customer_Age'] + 1
df_clean_year_2['Months_on_book'] = df_clean['Months_on_book'] + 12
df_clean_year_2_X = df_clean_year_2[df_clean_year_2.columns[1:]]

In [184]:
df_clean_year_2_pred = pd.DataFrame(RFC.predict_proba(df_clean_year_2_X)[:, 1])
df_clean_year_1_pred = pd.DataFrame(RFC.predict_proba(df_clean_year_2_X)[:, 1])

In [186]:
df_clean_X

,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,45,1,3,0,0,2,0,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,49,0,5,1,1,0,0,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,51,1,3,1,0,3,0,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,40,0,4,0,3,0,0,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,40,1,3,2,0,2,0,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,50,1,2,1,1,1,0,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,41,1,2,6,2,1,0,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,44,0,1,0,0,0,0,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,30,1,2,1,3,1,0,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,43,0,2,1,0,0,1,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [185]:
df_clean_year_2_pred

         0
0     0.01
1     0.02
2     0.08
3     0.08
4     0.24
...    ...
9229  0.57
9230  0.84
9231  0.81
9232  0.60
9233  0.71

[9234 rows x 1 columns]

Research on how credit card companies make money. 
Assumptions:
The credit card company is American Express. This is based on what tier cards are in the data. Blue, Silver, Gold, and Platinum.
On average Amex makes 2.3% - 3.5% on each transaction. Customers with higher trsaction amounts will bring in more revenue. (could do a low case and a high case)
Customers that carry a balance will bring in interest revenue.

In [53]:
year_1 = df

In [74]:
year_1.columns

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio'],
      dtype='object')

In [89]:
year_1_demo = ['Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon']
predict = ['Credit_Limit']

In [90]:
year_1_X = year_1[year_1_demo]
year_1_Y = year_1[predict]

In [101]:
year_2_X = year_1_X.copy()
year_2_X['Customer_Age'] = year_2_X['Customer_Age'] + 1
year_2_X['Months_on_book'] = year_2_X['Months_on_book'] + 12

In [112]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(year_1_X, year_1_Y, test_size=0.2, random_state=42)

In [113]:
from sklearn.ensemble import RandomForestRegressor

# Create the classifier
RFR = RandomForestRegressor()

# Fit the classifier to the training data
RFR.fit(X_train, y_train)

# Predict on the test data
year_1_credit_limit_pred = RFR.predict(X_test)

C:\Users\nfs25\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [114]:
score = RFR.score(X_test, y_test)
print("Model Score:", score)

Model Score: 0.5576408682263667

In [117]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

RFR = RandomForestRegressor()

# Create the GridSearchCV object
grid_search = GridSearchCV(estimator=RFR, param_grid=param_grid, cv=5, n_jobs=-1)

# Fit the GridSearchCV object to the training data
grid_search.fit(X_train, y_train)

# Get the best parameters and best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Print the best parameters and best score
print("Best Parameters:", best_params)
print("Best Score:", best_score)

C:\Users\nfs25\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Best Parameters: {'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 200}
Best Score: 0.5751586758473739

Take year one data and train a model that uses know delta varables that will predict each of the varable features. 

alter know delta varables to make part of year 2 data. 

use orginal model to predict other features